server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #sentinela主要分为两个核心部分，客户端和核心库，核心库就是那个官网下的jar包，客户端就是本项目模块
    sentinel:
      transport:
        #8401：微服务端口  8080：sentinel前台展示端口  8719：sentinel后台监控端口
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口，这个是后台监控端口
        port: 8719
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'